<div id="containeradmin">
    <div class="navAdmin">
        <ul>
          <li><button id="users"> Gestion des utilisateurs </button></li>
          <li><button id="accueil"> Gestion des messages d'accueil </button></li>
          <li><button id="creations"> Mes cr&eacute;ations </button></li>
          <li><button id="tuto"> Gestion des articles tutoriels </button></li>
        </ul>    
    </div>
<!-- Container for accueil data -->
    <div id="adminAccueil" class="hidden hide">
        <div class="adminBlock">
            <div class="adminTitle"><?= htmlspecialchars($presentation['presentationTitle']); ?></div>
            <div class="adminContent"><?= htmlspecialchars($presentation['presentationContent']); ?></div>
        </div>
        <div class="adminBlock">
            <div class="adminTitle"><?= htmlspecialchars($evenement['evenementTitle']); ?></div>
            <div class="adminContent"><?= htmlspecialchars($evenement['evenementContent']); ?></div>
        </div>
        <div class="adminBlock">
            <div class="adminTitle"><?= htmlspecialchars($news['newsTitle']); ?></div>
            <div class="adminContent"><?= htmlspecialchars($news['newsContent']); ?></div>
        </div>
    </div>

<!-- Container for creation data -->

    <div id="adminCreation" class="hidden hide">
        <?php foreach($creations as $creation): ?>
            <div>
                <div class="adminTitle"><?= htmlspecialchars($creation['creaTitle']); ?></div>
                <div class="adminContent"><?= htmlspecialchars($creation['creaDescription']); ?></div>
                <div class="adminImg">
                    <figure>
                        <img src="img/crea/<?= htmlspecialchars($creation['img']);?>">
                    </figure>
                </div>
            </div>
        <?php endforeach; ?>
    </div>

<!-- Container for users data -->

    <div id="adminUsers" class="hidden hide">
        <table>
            <thead>
                <tr>
                    <th colspan="2">Utilisateurs enregistrés</th>
                </tr>
                <tr>
                    <td>Nom d'utilisateurs</td>
                    <td>Email d'utilisateurs</td>
                    <td>statut d'utilisateurs</td>
                </tr>
            </thead>
            <tbody>
                <?php foreach($users as $user): ?>
                    <tr>
                <td><?= htmlspecialchars($user['username']); ?></td>
                <td><?= htmlspecialchars($user['email']); ?></td>
                <td><?= htmlspecialchars($user['userStatut']); ?></td>
                    </tr>
                <?php endforeach; ?>
        </table>
    </div>

<!-- Container for tutos data -->

    <div id="adminTutos" class="hidden hide">
        <?php foreach($tutos as $tuto): ?>
            <div>
                <div class="adminTitle"><?= htmlspecialchars($tuto['tutoTitle']); ?></div>
                <div class="adminContent"><?= htmlspecialchars($tuto['tutoText']); ?></div>
                <div><small><?= 'cr&eacute;&eacute; le ' . date('D-d-m-Y',strtotime(htmlspecialchars($tuto['createdAt']))); ?> </div></div>
            </div>
        <?php endforeach; ?>
    </div>

</div>

<script src="<?=asset('javascript/jquery-3.5.1.min')?>"></script>
<script src="<?=asset('javascript/main.js')?>"></script>
