<!DOCTYPE html>
<html lang="fr" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1 shrink-to-fit=no" />
    <title>Les cr&eacute;ations d'Absolem</title>
    <link href="css/style.css" rel="stylesheet">

</head>

<body>
    <header>
        <div class="ban">
            <div class="banniere">
                <h1>Page d'accueil et de redirection.</h1>
            </div>
            <div class="navbar">
                 <ul><button class="navdrop">Menu</button>
                  <div class="dropdown-content">
                    <li><a href="index.php" class="accueil">accueil</a></li>
                    <li><a href="crea.php" class="crea">cr&eacute;ations</a></li>
                    <li><a href="contact.php" class="contacts">contacts</a></li>
                    <li><a href="tuto.php" class="tutos">tutoriels</a></li>
                    <li><a href="login.php" class="connect">se connecter/s'inscrire</a></li>
                    <?php /* if isauthenticated and username = admin  */ ?><li><a href="admin.php" class="admin">Ma page administrateur</a></li>
                </div></ul>
            </div>
        </div>
    </header>

    <main>
        <?php include VIEWS_DIR . '/' . $view .'.phtml'; ?>
    </main>
    
    <footer class="foot">
        <div>
            <p>Site créé par Baptiste Giorgi &copy;</p>
        </div>
    </footer>
</body>

</html>