<!-- Formulaire de prise de contact pour envoyer un message a l'administrateur. -->

<div class="containercontact">
    <div class="contact">
    <form action="contact.php" method="post">
        <div class="form-group">
          <label for="prenom">Votre pr&eacute;nom :</label>
          <div><input type="text" name="prenom" id="prenom"></div>
          <label for="message">Votre message :</label>
          <div><textarea rows="8" cols="45" name="message" id="message"> </textarea></div>
        </div>
        <p class="form-button">
          <input type="submit" class="btn" value="Envoyer">
        </p>
      </form>
    </div>
    <div class="contactdata">
        <ul>
            <li>Retrouvez moi sur facebook: </li>
            <li>Ou par mail: </li>
            <li>Et par téléphone au: </li>
        </ul>
    </div>
</div>