<div class="containertutorial">

<!-- on récupère l'ensemble des articles en parcourant le tableau $tutos-->

    <?php foreach($tutos as $tuto): ?>
        <div class="tutorial">
            <div class="tutoTitle"><?= htmlspecialchars($tuto['tutoTitle']); ?>
            </div>
            <div class="tutoText"><?= htmlspecialchars($tuto['tutoText']); ?>
            </div>
        </div>
    <?php endforeach; ?>
</div>