<header>
    <h2>Modifier un  article</h2>
</header>
<section>
    <form action="<?=buildUrl('/admin/edit/evenement');?>" method="post">
        <fieldset>
            <div>
                <label for="title">Titre de la présentation</label>
                <input type="text" id="evenementTitle" name="evenementTitle" value="<?=$evenement['evenementTitle'];?>">
            </div>
            <div>
                <label for="content">Modifier ma présentation</label>
                <textarea  rows="8" cols="45" id="evenementContent" name="evenementContent"><?=$evenement['evenementContent'];?></textarea>
            </div>
        </fieldset>
        <input type="submit" value="Enregistrer">
    </form>

</section>